# Generated by Django 5.1.7 on 2025-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
