# Generated by Django 5.1.7 on 2025-04-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_adminuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='blockchain_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
